### ISSUE TITLE
能用，但爬视频信息会显示风控

### ISSUE THREAD

**Issue by boyue2999** [jiashi19/biliSpider#1]
{'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': '

**Comment by jiashi19** [comment]
> {'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': '

看看videoscrapy.py里面的值填好了没有呢

**Comment by jiashi19** [comment]
> > {'code': -352, 'message': '风控校验失败', 'ttl': 1, 'data': {'v_voucher': '
> 
> 看看videoscrapy.py里面的值填好了没有呢

我刚刚试了下还可以用，你看看是cookie没填好还是使用过于频繁导致cookie请求api被封禁。
